# Generated by Django 4.2.25 on 2025-10-22 23:33

from django.db import migrations, models
import solicitudes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Formato: 12345678-9 (sin puntos, con guión)', max_length=12, unique=True, validators=[solicitudes.models.validar_rut], verbose_name='RUT')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(help_text='Formato: +56912345678 o 912345678', max_length=15, validators=[solicitudes.models.validar_telefono], verbose_name='Teléfono')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aceptación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
